In [8]:
f=open('ab.txt','w')
print('file name:',f.name)
print('file mode:',f.mode)
print(f.readable())
print(f.writable())
print(f.closed)
f.close()
print(f.closed)

file name: ab.txt
file mode: w
False
True
False
True


In [18]:
with open("ab.txt","r")as ai:
    content=ai.read()
print(content)

aditya degree college
kakinada
artificial intelligence


In [19]:
with open("ab.txt","r")as ai:
    content=ai.read(6)
print(content)

aditya


In [20]:
with open("ab.txt","r")as ai:
    content=ai.readline()
print(content)

aditya degree college



In [21]:
with open("ab.txt","r")as ai:
    content=ai.readlines()
print(content)

['aditya degree college\n', 'kakinada\n', 'artificial intelligence']


In [22]:
with open("ab.txt","w")as ai:
    ai.write("aditya degree college")

In [24]:
l=["aditya degree college\n","kakinada\n","artificial intelligence"]
with open("ab.txt","w")as ai:
    ai.write("aditya degree college")

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
l=range(100)
%timeit [i**2 for i in l]

15.1 µs ± 790 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
a=np.arange(100)
%timeit a**2

1.58 µs ± 269 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# creating arrays

In [9]:
a=np.array([1,2,3,4])#one dimensional array


In [11]:
print(a.ndim)

1


In [13]:
b=np.array([[1,2,3,],[4,5,6]])#two dimension

In [14]:
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
print(b.ndim)

2


In [19]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])#three dimension

In [20]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [21]:
c.ndim

3

In [22]:
a.shape#displays no of coloumn

(4,)

In [23]:
b.shape

(2, 3)

In [24]:
c.shape

(1, 3, 3)

# functions for creating array

In [28]:
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [29]:
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [30]:
a=np.ones((3,3,))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
a=np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [37]:
a=np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [38]:
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [39]:
np.diag(a)

array([1, 2, 3, 4, 5])

# basic dataa types

In [42]:
a=np.arange(10)
a.dtype

dtype('int32')

In [44]:
a=np.arange(10,dtype="float")
a.dtype

dtype('float64')

In [46]:
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

# other datatypes

In [47]:
a=np.array([1+2j,2+4j])
a.dtype

dtype('complex128')

In [48]:
a=np.array([True,False])
a.dtype

dtype('bool')

In [49]:
a=np.array(['prashanthi','kesanakurthi'])
a.dtype

dtype('<U12')

# indexing and slicing

In [51]:
a=np.arange(10)
a[5]

5

In [52]:
a=np.diag([1,2,3])
a[2,2]

3

In [54]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

# Slicing

In [55]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a[1:8:2]

array([1, 3, 5, 7])

In [57]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

# copies and viewing

In [59]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [60]:
np.shares_memory(a,b)

True

In [61]:
b[0]=10
print(a) #viewing
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [63]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [64]:
b[0]=10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# random number generator

In [65]:
a=np.random.randint(0,20,15)
a

array([11,  6,  0, 14,  1,  7, 13, 14,  8,  5, 14,  1, 16, 17,  0])

In [66]:
mask=(a%2==0)

In [67]:
mask_a=a[mask]
print(mask_a)

[ 6  0 14 14  8 14 16  0]


In [68]:
a[mask]=-1
a

array([11, -1, -1, -1,  1,  7, 13, -1, -1,  5, -1,  1, -1, 17, -1])

# pandas

In [ ]:
works like excel but faster
helps load, clean, filter,analyze data
uses= datascince machine learning finance analytics and automating data tasks

# import pandas

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'2.0.3'

# pandas Data Structures

## series- one dimensional column
## DataFrame-Table with rows+columns

In [2]:
s=pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [5]:
df=pd.DataFrame({
    "name":["ramya","prashanthi"],
    "age":[20,19]
})
df

name  age
0       ramya   20
1  prashanthi   19

# Reading data(CSV)

In [9]:
df=pd.read_csv(r"C:\Users\prashanthi\OneDrive\Pictures\文档\RESULT (1).csv")
df

NUMBER STUDENT NAME  MATHEMATICS V 6A  MV6AGrade points  \
0   2.103772e+11          NaN               NaN               0.0   
1   2.103772e+11          NaN               NaN               0.0   
2   2.103772e+11          NaN               NaN               0.0   
3   2.103772e+11          NaN               NaN               0.0   
4   2.103772e+11          NaN               NaN               0.0   
5   2.103772e+11          NaN               NaN               0.0   
6   2.103772e+11          NaN               NaN               0.0   
7   2.103772e+11          NaN               NaN               0.0   
8   2.103772e+11          NaN               NaN               0.0   
9   2.103772e+11          NaN               NaN               0.0   
10  2.103772e+11          NaN               NaN               0.0   
11  2.103772e+11          NaN               NaN               0.0   
12  2.103772e+11          NaN               NaN               0.0   
13  2.103772e+11          NaN               NaN               0.0   
14  2.103772e+11          NaN               NaN               0.0   
15  2.103772e+11          NaN               NaN               0.0   
16  2.103772e+11          NaN               NaN               0.0   
17  2.103772e+11          NaN               NaN               0.0   
18  2.103772e+11          NaN               NaN               0.0   
19  2.103772e+11          NaN               NaN               0.0   
20  2.103772e+11          NaN               NaN               0.0   
21  2.103872e+11          NaN               NaN               0.0   
22  2.102172e+11          NaN               NaN               0.0   
23  2.103772e+11          NaN               NaN               0.0   
24  2.103772e+11          NaN               NaN               0.0   
25  2.103772e+11          NaN               NaN               0.0   
26  2.103772e+11          NaN               NaN               0.0   
27  2.102172e+11          NaN               NaN               0.0   
28  2.103772e+11          NaN               NaN               0.0   
29  2.103772e+11          NaN               NaN               0.0   
30  2.103772e+11          NaN               NaN               0.0   
31  2.102172e+11          NaN               NaN               0.0   
32  2.103772e+11          NaN               NaN               0.0   
33  2.103772e+11          NaN               NaN               0.0   
34  2.103772e+11          NaN               NaN               0.0   
35  2.103772e+11          NaN               NaN               0.0   
36  2.103772e+11          NaN               NaN               0.0   
37  2.102172e+11          NaN               NaN               0.0   
38  2.103772e+11          NaN               NaN               0.0   
39  2.103772e+11          NaN               NaN               0.0   
40  2.103772e+11          NaN               NaN               0.0   
41  2.103772e+11          NaN               NaN               0.0   
42  2.103772e+11          NaN               NaN               0.0   
43  2.102172e+11          NaN               NaN               0.0   
44  2.103772e+11          NaN               NaN               0.0   
45  2.103772e+11          NaN               NaN               0.0   
46           NaN     ANALYSIS               NaN               NaN   
47           NaN    "O" GRADE               0.0               0.0   
48           NaN   "A+" GRADE               0.0               NaN   
49           NaN    "A" GRADE               0.0               NaN   
50           NaN   "B+" GRADE               0.0               NaN   
51           NaN    "B" GRADE               0.0               NaN   
52           NaN    "C" GRADE               0.0               NaN   
53           NaN    "D" GRADE               0.0               NaN   
54           NaN    "F" GRADE               0.0               NaN   

    MATHEMATICS V 7A  MV7AGrade points  COMPUTER SCIENCE V 6A  \
0                NaN               0.0                    NaN   
1              

In [20]:
df.to_csv("data.csv",index=False)
df

NUMBER STUDENT NAME  MATHEMATICS V 6A  MV6AGrade points  \
0   2.103772e+11          NaN               NaN               0.0   
1   2.103772e+11          NaN               NaN               0.0   
2   2.103772e+11          NaN               NaN               0.0   
3   2.103772e+11          NaN               NaN               0.0   
4   2.103772e+11          NaN               NaN               0.0   
5   2.103772e+11          NaN               NaN               0.0   
6   2.103772e+11          NaN               NaN               0.0   
7   2.103772e+11          NaN               NaN               0.0   
8   2.103772e+11          NaN               NaN               0.0   
9   2.103772e+11          NaN               NaN               0.0   
10  2.103772e+11          NaN               NaN               0.0   
11  2.103772e+11          NaN               NaN               0.0   
12  2.103772e+11          NaN               NaN               0.0   
13  2.103772e+11          NaN               NaN               0.0   
14  2.103772e+11          NaN               NaN               0.0   
15  2.103772e+11          NaN               NaN               0.0   
16  2.103772e+11          NaN               NaN               0.0   
17  2.103772e+11          NaN               NaN               0.0   
18  2.103772e+11          NaN               NaN               0.0   
19  2.103772e+11          NaN               NaN               0.0   
20  2.103772e+11          NaN               NaN               0.0   
21  2.103872e+11          NaN               NaN               0.0   
22  2.102172e+11          NaN               NaN               0.0   
23  2.103772e+11          NaN               NaN               0.0   
24  2.103772e+11          NaN               NaN               0.0   
25  2.103772e+11          NaN               NaN               0.0   
26  2.103772e+11          NaN               NaN               0.0   
27  2.102172e+11          NaN               NaN               0.0   
28  2.103772e+11          NaN               NaN               0.0   
29  2.103772e+11          NaN               NaN               0.0   
30  2.103772e+11          NaN               NaN               0.0   
31  2.102172e+11          NaN               NaN               0.0   
32  2.103772e+11          NaN               NaN               0.0   
33  2.103772e+11          NaN               NaN               0.0   
34  2.103772e+11          NaN               NaN               0.0   
35  2.103772e+11          NaN               NaN               0.0   
36  2.103772e+11          NaN               NaN               0.0   
37  2.102172e+11          NaN               NaN               0.0   
38  2.103772e+11          NaN               NaN               0.0   
39  2.103772e+11          NaN               NaN               0.0   
40  2.103772e+11          NaN               NaN               0.0   
41  2.103772e+11          NaN               NaN               0.0   
42  2.103772e+11          NaN               NaN               0.0   
43  2.102172e+11          NaN               NaN               0.0   
44  2.103772e+11          NaN               NaN               0.0   
45  2.103772e+11          NaN               NaN               0.0   
46           NaN     ANALYSIS               NaN               NaN   
47           NaN    "O" GRADE               0.0               0.0   
48           NaN   "A+" GRADE               0.0               NaN   
49           NaN    "A" GRADE               0.0               NaN   
50           NaN   "B+" GRADE               0.0               NaN   
51           NaN    "B" GRADE               0.0               NaN   
52           NaN    "C" GRADE               0.0               NaN   
53           NaN    "D" GRADE               0.0               NaN   
54           NaN    "F" GRADE               0.0               NaN   

    MATHEMATICS V 7A  MV7AGrade points  COMPUTER SCIENCE V 6A  \
0                NaN               0.0                    NaN   
1              

In [17]:
df.head()

NUMBER STUDENT NAME  MATHEMATICS V 6A  MV6AGrade points  \
0  2.103772e+11          NaN               NaN               0.0   
1  2.103772e+11          NaN               NaN               0.0   
2  2.103772e+11          NaN               NaN               0.0   
3  2.103772e+11          NaN               NaN               0.0   
4  2.103772e+11          NaN               NaN               0.0   

   MATHEMATICS V 7A  MV7AGrade points  COMPUTER SCIENCE V 6A  \
0               NaN               0.0                    NaN   
1               NaN               0.0                    NaN   
2               NaN               0.0                    NaN   
3               NaN               0.0                    NaN   
4               NaN               0.0                    NaN   

   CSV6AGrade points  COMPUTER SCIENCE V 6A PRACTICALS  CS6APGrade points  \
0                0.0                               NaN                0.0   
1                0.0                               NaN                0.0   
2                0.0                               NaN                0.0   
3                0.0                               NaN                0.0   
4                0.0                               NaN                0.0   

   ...  AIRV6CGrade points  AI AND ROBOTICS V 6C PRACTICALS  \
0  ...                 0.0                              NaN   
1  ...                 0.0                              NaN   
2  ...                 0.0                              NaN   
3  ...                 0.0                              NaN   
4  ...                 0.0                              NaN   

   AIRV6CPGrade points  AI AND ROBOTICS V 7C  AIRV7CGrade points  \
0                  0.0                   NaN                 0.0   
1                  0.0                   NaN                 0.0   
2                  0.0                   NaN                 0.0   
3                  0.0                   NaN                 0.0   
4                  0.0                   NaN                 0.0   

   AI AND ROBOTICS V 7C PRACTICALS  AIRV7CPGrade points  CGPA  PASS or FAIL  \
0                              NaN                  0.0   0.0          FAIL   
1                              NaN                  0.0   0.0          FAIL   
2                              NaN                  0.0   0.0          FAIL   
3                              NaN                  0.0   0.0          FAIL   
4                              NaN                  0.0   0.0          FAIL   

   NO OF BACKLOGS  
0            10.0  
1            10.0  
2            10.0  
3            10.0  
4            10.0  

[5 rows x 25 columns]

In [19]:
df.tail()

NUMBER STUDENT NAME  MATHEMATICS V 6A  MV6AGrade points  MATHEMATICS V 7A  \
50     NaN   "B+" GRADE               0.0               NaN               0.0   
51     NaN    "B" GRADE               0.0               NaN               0.0   
52     NaN    "C" GRADE               0.0               NaN               0.0   
53     NaN    "D" GRADE               0.0               NaN               0.0   
54     NaN    "F" GRADE               0.0               NaN               0.0   

    MV7AGrade points  COMPUTER SCIENCE V 6A  CSV6AGrade points  \
50               NaN                    0.0                NaN   
51               NaN                    0.0                NaN   
52               NaN                    0.0                NaN   
53               NaN                    0.0                NaN   
54               NaN                    0.0                NaN   

    COMPUTER SCIENCE V 6A PRACTICALS  CS6APGrade points  ...  \
50                               0.0                NaN  ...   
51                               0.0                NaN  ...   
52                               0.0                NaN  ...   
53                               0.0                NaN  ...   
54                               0.0                NaN  ...   

    AIRV6CGrade points  AI AND ROBOTICS V 6C PRACTICALS  AIRV6CPGrade points  \
50                 NaN                              0.0                  NaN   
51                 NaN                              0.0                  NaN   
52                 NaN                              0.0                  NaN   
53                 NaN                              0.0                  NaN   
54                 NaN                              0.0                  NaN   

    AI AND ROBOTICS V 7C  AIRV7CGrade points  AI AND ROBOTICS V 7C PRACTICALS  \
50                   0.0                 NaN                              0.0   
51                   0.0                 NaN                              0.0   
52                   0.0                 NaN                              0.0   
53                   0.0                 NaN                              0.0   
54                   0.0                 NaN                              0.0   

    AIRV7CPGrade points  CGPA  PASS or FAIL  NO OF BACKLOGS  
50                  NaN   NaN           NaN             NaN  
51                  NaN   NaN           NaN             NaN  
52                  NaN   NaN           NaN             NaN  
53                  NaN   NaN           NaN             NaN  
54                  NaN   NaN           NaN             NaN  

[5 rows x 25 columns]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 25 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   NUMBER                            46 non-null     float64
 1   STUDENT NAME                      9 non-null      object 
 2   MATHEMATICS V 6A                  8 non-null      float64
 3   MV6AGrade points                  47 non-null     float64
 4   MATHEMATICS V 7A                  8 non-null      float64
 5   MV7AGrade points                  47 non-null     float64
 6   COMPUTER SCIENCE V 6A             8 non-null      float64
 7   CSV6AGrade points                 47 non-null     float64
 8   COMPUTER SCIENCE V 6A PRACTICALS  8 non-null      float64
 9   CS6APGrade points                 47 non-null     float64
 10  COMPUTER SCIENCE V 7A             8 non-null      float64
 11  CSV7AGrade points                 47 non-null     float64
 12  COMPUTER S

In [22]:
df.shape

(55, 25)

In [23]:
df.dtypes

NUMBER                              float64
STUDENT NAME                         object
MATHEMATICS V 6A                    float64
MV6AGrade points                    float64
MATHEMATICS V 7A                    float64
MV7AGrade points                    float64
COMPUTER SCIENCE V 6A               float64
CSV6AGrade points                   float64
COMPUTER SCIENCE V 6A PRACTICALS    float64
CS6APGrade points                   float64
COMPUTER SCIENCE V 7A               float64
CSV7AGrade points                   float64
COMPUTER SCIENCE V 7A PRACTICALS    float64
CSV7APGrade points                  float64
AI AND ROBOTICS V 6C                float64
AIRV6CGrade points                  float64
AI AND ROBOTICS V 6C PRACTICALS     float64
AIRV6CPGrade points                 float64
AI AND ROBOTICS V 7C                float64
AIRV7CGrade points                  float64
AI AND ROBOTICS V 7C PRACTICALS     float64
AIRV7CPGrade points                 float64
CGPA                            

In [24]:
df.index

RangeIndex(start=0, stop=55, step=1)

In [25]:
df.CGPA

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
21    0.0
22    0.0
23    0.0
24    0.0
25    0.0
26    0.0
27    0.0
28    0.0
29    0.0
30    0.0
31    0.0
32    0.0
33    0.0
34    0.0
35    0.0
36    0.0
37    0.0
38    0.0
39    0.0
40    0.0
41    0.0
42    0.0
43    0.0
44    0.0
45    0.0
46    NaN
47    0.0
48    NaN
49    NaN
50    NaN
51    NaN
52    NaN
53    NaN
54    NaN
Name: CGPA, dtype: float64

In [26]:
df[['CGPA','NO OF BACKLOGS']]

CGPA  NO OF BACKLOGS
0    0.0            10.0
1    0.0            10.0
2    0.0            10.0
3    0.0            10.0
4    0.0            10.0
5    0.0            10.0
6    0.0            10.0
7    0.0            10.0
8    0.0            10.0
9    0.0            10.0
10   0.0            10.0
11   0.0            10.0
12   0.0            10.0
13   0.0            10.0
14   0.0            10.0
15   0.0            10.0
16   0.0            10.0
17   0.0            10.0
18   0.0            10.0
19   0.0            10.0
20   0.0            10.0
21   0.0            10.0
22   0.0            10.0
23   0.0            10.0
24   0.0            10.0
25   0.0            10.0
26   0.0            10.0
27   0.0            10.0
28   0.0            10.0
29   0.0            10.0
30   0.0            10.0
31   0.0            10.0
32   0.0            10.0
33   0.0            10.0
34   0.0            10.0
35   0.0            10.0
36   0.0            10.0
37   0.0            10.0
38   0.0            10.0
39   0.0            10.0
40   0.0            10.0
41   0.0            10.0
42   0.0            10.0
43   0.0            10.0
44   0.0            10.0
45   0.0            10.0
46   NaN             NaN
47   0.0             NaN
48   NaN             NaN
49   NaN             NaN
50   NaN             NaN
51   NaN             NaN
52   NaN             NaN
53   NaN             NaN
54   NaN             NaN

# MISSING VALUES

In [27]:
df.isnull()

NUMBER  STUDENT NAME  MATHEMATICS V 6A  MV6AGrade points  \
0    False          True              True             False   
1    False          True              True             False   
2    False          True              True             False   
3    False          True              True             False   
4    False          True              True             False   
5    False          True              True             False   
6    False          True              True             False   
7    False          True              True             False   
8    False          True              True             False   
9    False          True              True             False   
10   False          True              True             False   
11   False          True              True             False   
12   False          True              True             False   
13   False          True              True             False   
14   False          True              True             False   
15   False          True              True             False   
16   False          True              True             False   
17   False          True              True             False   
18   False          True              True             False   
19   False          True              True             False   
20   False          True              True             False   
21   False          True              True             False   
22   False          True              True             False   
23   False          True              True             False   
24   False          True              True             False   
25   False          True              True             False   
26   False          True              True             False   
27   False          True              True             False   
28   False          True              True             False   
29   False          True              True             False   
30   False          True              True             False   
31   False          True              True             False   
32   False          True              True             False   
33   False          True              True             False   
34   False          True              True             False   
35   False          True              True             False   
36   False          True              True             False   
37   False          True              True             False   
38   False          True              True             False   
39   False          True              True             False   
40   False          True              True             False   
41   False          True              True             False   
42   False          True              True             False   
43   False          True              True             False   
44   False          True              True             False   
45   False          True              True             False   
46    True         False              True              True   
47    True         False             False             False   
48    True         False             False              True   
49    True         False             False              True   
50    True         False             False              True   
51    True         False             False              True   
52    True         False             False              True   
53    True         False             False              True   
54    True         False             False              True   

    MATHEMATICS V 7A  MV7AGrade points  COMPUTER SCIENCE V 6A  \
0               True             False                   True   
1               True             False                   True   
2               True             False                   True   
3               True             False                   True   
4               True             False                   True   
5               True         

In [56]:
df=pd.DataFrame({
    "name":["prashanthi","ramya","devi"],
    "age":[10,12,None]
})
df

name   age
0  prashanthi  10.0
1       ramya  12.0
2        devi   NaN

In [51]:
df.isnull().sum()

name    0
age     1
dtype: int64

In [52]:
df[df.isnull().any(axis=1)]

name  age
2  devi  NaN

In [53]:
df['age']=df['age'].fillna(df['age'].mean())

In [54]:
df

name   age
0  prashanthi  10.0
1       ramya  12.0
2        devi  11.0

In [57]:
dfclean=df.dropna()
dfclean

name   age
0  prashanthi  10.0
1       ramya  12.0

# Duplicates

In [58]:
df=pd.DataFrame({
    "name":["prash","prash","devs"],
    "age":[25,25,24]
})
df

name  age
0  prash   25
1  prash   25
2   devs   24

In [59]:
df.duplicated()

0    False
1     True
2    False
dtype: bool

In [60]:
df[df.duplicated()]

name  age
1  prash   25

In [61]:
df=df.drop_duplicates()
df

name  age
0  prash   25
2   devs   24

# missing values

In [1]:
import pandas as pd

In [11]:
df=pd.read_csv(r"C:\Users\prashanthi\Downloads\data.csv")

In [12]:
df

NAME CLASS SECTION  ROLLNO                            EMAIL  \
0        B.Yamuna   AIR       A      37          yamunalovely9@gmail.com   
1          P.Devi   AIR       A      58     gundrasivesaidurga@gmail.com   
2        J.Ramya    AIR     NaN      52      jivvireddyramyasri@gmailcom   
3     K.Prasanthi   AIR       A      41  kesanakurthiprasanthi@gmail.com   
4   K.V. Niharika   AIR       A      54     karreveeraniharika@gmail.com   
5  K.Sri Niharika   AIR       A       9       karresriniharika@gmail.com   
6        Y.Kaveri   AIR     NaN       3        yendamurikaveri@gmail.com   
7         P.Durga   AIR       A      24              durgarani@gmail.com   
8        P.Akhila   AIR       A      29            bottaakhila@gmail.com   
9       P.Neelima   AIR       A      36         pinapalaramesh@gmail.com   

         PHNO  MARKS  
0  8897859569    NaN  
1  9347791232   97.0  
2  9676976652    NaN  
3  7382934586   85.0  
4  9182532802   96.0  
5  6300408089   90.0  
6  7386015549    NaN  
7  8466845651   89.0  
8  8397941799   90.0  
9  7386803023    NaN

In [13]:
df.isnull()

NAME  CLASS  SECTION  ROLLNO                 EMAIL   PHNO  MARKS
0  False  False    False   False                 False  False   True
1  False  False    False   False                 False  False  False
2  False  False     True   False                 False  False   True
3  False  False    False   False                 False  False  False
4  False  False    False   False                 False  False  False
5  False  False    False   False                 False  False  False
6  False  False     True   False                 False  False   True
7  False  False    False   False                 False  False  False
8  False  False    False   False                 False  False  False
9  False  False    False   False                 False  False   True

In [14]:
df.isnull().sum()

NAME                    0
CLASS                   0
SECTION                 2
ROLLNO                  0
               EMAIL    0
PHNO                    0
MARKS                   4
dtype: int64

In [15]:
df_clean=df.dropna()

In [7]:
df_clean

NAME CLASS SECTION  ROLLNO                            EMAIL  \
0        B.Yamuna   AIR       A      37          yamunalovely9@gmail.com   
1          P.Devi   AIR       A      58     gundrasivesaidurga@gmail.com   
2        J.Ramya    AIR       A      52      jivvireddyramyasri@gmailcom   
3     K.Prasanthi   AIR       A      41  kesanakurthiprasanthi@gmail.com   
4   K.V. Niharika   AIR       A      54     karreveeraniharika@gmail.com   
5  K.Sri Niharika   AIR       A       9       karresriniharika@gmail.com   
6        Y.Kaveri   AIR       A       3        yendamurikaveri@gmail.com   
7         P.Durga   AIR       A      24              durgarani@gmail.com   
8        P.Akhila   AIR       A      29            bottaakhila@gmail.com   
9       P.Neelima   AIR       A      36         pinapalaramesh@gmail.com   

         PHNO  MARKS  
0  8897859569     95  
1  9347791232     97  
2  9676976652     90  
3  7382934586     85  
4  9182532802     96  
5  6300408089     90  
6  7386015549     94  
7  8466845651     89  
8  8397941799     90  
9  7386803023     93

In [16]:
df

NAME CLASS SECTION  ROLLNO                            EMAIL  \
0        B.Yamuna   AIR       A      37          yamunalovely9@gmail.com   
1          P.Devi   AIR       A      58     gundrasivesaidurga@gmail.com   
2        J.Ramya    AIR     NaN      52      jivvireddyramyasri@gmailcom   
3     K.Prasanthi   AIR       A      41  kesanakurthiprasanthi@gmail.com   
4   K.V. Niharika   AIR       A      54     karreveeraniharika@gmail.com   
5  K.Sri Niharika   AIR       A       9       karresriniharika@gmail.com   
6        Y.Kaveri   AIR     NaN       3        yendamurikaveri@gmail.com   
7         P.Durga   AIR       A      24              durgarani@gmail.com   
8        P.Akhila   AIR       A      29            bottaakhila@gmail.com   
9       P.Neelima   AIR       A      36         pinapalaramesh@gmail.com   

         PHNO  MARKS  
0  8897859569    NaN  
1  9347791232   97.0  
2  9676976652    NaN  
3  7382934586   85.0  
4  9182532802   96.0  
5  6300408089   90.0  
6  7386015549    NaN  
7  8466845651   89.0  
8  8397941799   90.0  
9  7386803023    NaN

In [18]:
df['MARKS']=df['MARKS'].fillna(df['MARKS'].mean())

In [20]:
df

NAME CLASS SECTION  ROLLNO                            EMAIL  \
0        B.Yamuna   AIR       A      37          yamunalovely9@gmail.com   
1          P.Devi   AIR       A      58     gundrasivesaidurga@gmail.com   
2        J.Ramya    AIR     NaN      52      jivvireddyramyasri@gmailcom   
3     K.Prasanthi   AIR       A      41  kesanakurthiprasanthi@gmail.com   
4   K.V. Niharika   AIR       A      54     karreveeraniharika@gmail.com   
5  K.Sri Niharika   AIR       A       9       karresriniharika@gmail.com   
6        Y.Kaveri   AIR     NaN       3        yendamurikaveri@gmail.com   
7         P.Durga   AIR       A      24              durgarani@gmail.com   
8        P.Akhila   AIR       A      29            bottaakhila@gmail.com   
9       P.Neelima   AIR       A      36         pinapalaramesh@gmail.com   

         PHNO      MARKS  
0  8897859569  91.166667  
1  9347791232  97.000000  
2  9676976652  91.166667  
3  7382934586  85.000000  
4  9182532802  96.000000  
5  6300408089  90.000000  
6  7386015549  91.166667  
7  8466845651  89.000000  
8  8397941799  90.000000  
9  7386803023  91.166667

# mini project

In [21]:
df.head()

NAME CLASS SECTION  ROLLNO                            EMAIL  \
0       B.Yamuna   AIR       A      37          yamunalovely9@gmail.com   
1         P.Devi   AIR       A      58     gundrasivesaidurga@gmail.com   
2       J.Ramya    AIR     NaN      52      jivvireddyramyasri@gmailcom   
3    K.Prasanthi   AIR       A      41  kesanakurthiprasanthi@gmail.com   
4  K.V. Niharika   AIR       A      54     karreveeraniharika@gmail.com   

         PHNO      MARKS  
0  8897859569  91.166667  
1  9347791232  97.000000  
2  9676976652  91.166667  
3  7382934586  85.000000  
4  9182532802  96.000000

In [22]:
df.tail()

NAME CLASS SECTION  ROLLNO                       EMAIL  \
5  K.Sri Niharika   AIR       A       9  karresriniharika@gmail.com   
6        Y.Kaveri   AIR     NaN       3   yendamurikaveri@gmail.com   
7         P.Durga   AIR       A      24         durgarani@gmail.com   
8        P.Akhila   AIR       A      29       bottaakhila@gmail.com   
9       P.Neelima   AIR       A      36    pinapalaramesh@gmail.com   

         PHNO      MARKS  
5  6300408089  90.000000  
6  7386015549  91.166667  
7  8466845651  89.000000  
8  8397941799  90.000000  
9  7386803023  91.166667

In [23]:
df=pd.read_csv(r"C:\Users\prashanthi\Downloads\weather_data.csv")
df

Date          City  Temperature_C  Humidity_% Condition
0  01-01-2025      Hyderbad             28          60     Sunny
1  02-01-2025    Vijayawada             29          62     Sunny
2  03-01-2025  Viskhapatnam             30          58    Cloudy
3  04-01-2025      Kakinada             31          55    Cloudy
4  05-01-2025      Banglore             32          57     Rainy
5  06-01-2025        Mumbai             33          59     Rainy
6  07-01-2025       Chennai             34          61     Sunny
7  08-01-2025    Rajamundry             32          63    Cloudy
8  09-01-2025         Eluru             31          64     Rainy
9  10-01-2025    Anakapalli             29          62     Sunny

In [24]:
df.head()

Date          City  Temperature_C  Humidity_% Condition
0  01-01-2025      Hyderbad             28          60     Sunny
1  02-01-2025    Vijayawada             29          62     Sunny
2  03-01-2025  Viskhapatnam             30          58    Cloudy
3  04-01-2025      Kakinada             31          55    Cloudy
4  05-01-2025      Banglore             32          57     Rainy

In [25]:
df.tail()

Date        City  Temperature_C  Humidity_% Condition
5  06-01-2025      Mumbai             33          59     Rainy
6  07-01-2025     Chennai             34          61     Sunny
7  08-01-2025  Rajamundry             32          63    Cloudy
8  09-01-2025       Eluru             31          64     Rainy
9  10-01-2025  Anakapalli             29          62     Sunny

In [26]:
df.shape

(10, 5)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Date           10 non-null     object
 1   City           10 non-null     object
 2   Temperature_C  10 non-null     int64 
 3   Humidity_%     10 non-null     int64 
 4   Condition      10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes


In [28]:
df[2:5]

Date          City  Temperature_C  Humidity_% Condition
2  03-01-2025  Viskhapatnam             30          58    Cloudy
3  04-01-2025      Kakinada             31          55    Cloudy
4  05-01-2025      Banglore             32          57     Rainy

In [29]:
df.columns

Index(['Date', 'City', 'Temperature_C', 'Humidity_%', 'Condition'], dtype='object')

In [30]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [31]:
df.dtypes

Date             object
City             object
Temperature_C     int64
Humidity_%        int64
Condition        object
dtype: object

In [32]:
df.Date

0    01-01-2025
1    02-01-2025
2    03-01-2025
3    04-01-2025
4    05-01-2025
5    06-01-2025
6    07-01-2025
7    08-01-2025
8    09-01-2025
9    10-01-2025
Name: Date, dtype: object

In [33]:
df['Date']

0    01-01-2025
1    02-01-2025
2    03-01-2025
3    04-01-2025
4    05-01-2025
5    06-01-2025
6    07-01-2025
7    08-01-2025
8    09-01-2025
9    10-01-2025
Name: Date, dtype: object

In [36]:
df['Date'][df['Condition']=='Rainy']

4    05-01-2025
5    06-01-2025
8    09-01-2025
Name: Date, dtype: object

# exploring Data

In [37]:
ai=pd.DataFrame({
    "name":["prashanthi","devi","ramya"],
    "age":[23,25,30]
})
ai

name  age
0  prashanthi   23
1        devi   25
2       ramya   30

In [38]:
ds=pd.DataFrame({
    "name":["pritham","nikki","ramya"],
    "age":[30,25,35]
})
ds

name  age
0  pritham   30
1    nikki   25
2    ramya   35

In [42]:
a=pd.merge(ai,ds,on='name')
a

name  age_x  age_y
0  ramya     30     35

In [45]:
df=pd.concat([ai,ds],ignore_index=True)
df

name  age
0  prashanthi   23
1        devi   25
2       ramya   30
3     pritham   30
4       nikki   25
5       ramya   35